services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.go
    image: lucasassuncaobr/mira-go:latest
    container_name: mira-go
    ports:
      - "3333:3333"
    volumes:
      - ./apps/api/data:/app/data
    restart: always
    environment:
      - PORT=3333

