FROM php:8.4-apache
RUN a2enmod rewrite
RUN apt-get update && apt-get install -y libzip-dev libpng-dev libjpeg-dev libfreetype6-dev libonig-dev git unzip curl \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install pdo_mysql mysqli zip gd mbstring \
  && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
  && apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /var/www/html
# O código do Flarum já está em ./forum (montado via volume), não precisa copiar
# Apenas garante permissões e DocumentRoot
RUN sed -i 's|DocumentRoot /var/www/html|DocumentRoot /var/www/html/public|' /etc/apache2/sites-available/000-default.conf
RUN echo "ServerName forum.local" >> /etc/apache2/apache2.conf
EXPOSE 80
CMD ["apache2-foreground"]
